####################################################
# QuestionPy Application Server Configuration File #
####################################################

# This file shows all available settings with their corresponding default values commented out.

# Every setting can be overwritten by a corresponding environment variable. The environment variable has to
# follow the pattern "QPY_<SECTION>__<SETTING>" - section and setting are uppercased and separated by two underscores.
# E.g., the setting general->log_level can be overwritten by the environment variable QPY_GENERAL__LOG_LEVEL.

general:
  # The log level [NONE, DEBUG, INFO, WARNING, ERROR, CRITICAL]
  #log_level: INFO

webservice:
  # The address the http server should bind to
  #listen_address: 127.0.0.1

  # The port the http server should bind to
  #listen_port: 9020

  # Maximum package size (at least 20 MiB)
  #max_package_size: 20 MiB

  # Allow packages from the LMS
  #allow_lms_packages: true

worker_pool:
  # Fully qualified name of the worker class
  #type: questionpy_server.worker.impl.subprocess.SubprocessWorker

  # Maximum number of CPUs that can be used by all workers
  #max_cpus: 8

  # Maximum combined memory usage of all workers
  #max_memory: 500 MiB

permissions:
  # Permissions that are granted automatically
  #auto_grant_permissions:
    # Maximum number of CPUs that a worker can use
    #cpus: 1

    # Maximum memory usage of a worker (at least 200 MiB)
    #memory: 200 MiB

    # Allowed execution modes for the worker main process. Allowed values are:
    #  - container: executed in isolated containers
    #  - trusted: executed as a normal process (but with CPU and memory limits), implies unrestricted_network_access
    #main_process_execution_modes:
    #  - container

    # Maximum time in seconds per request (at least 10)
    #request_timeout: 10

    # Maximum time in seconds for the worker to start (at least 4)
    #bootstrap_timeout: 4

  # Package- and request-specific permissions
  # The following example would raise the auto_grant_permissions->memory of every package that is locally available and
  # has the namespace "qpy" to 1 GiB and every worker running these packages can use 2 CPUs even if the package
  # requested a different amount:
  # packages:
  #   - package_selector:
  #       origin:
  #         local: true
  #       namespace: "qpy"
  #     auto_grant_permissions:
  #       memory: 1 GiB
  #     override_permissions:
  #       cpus: 2
  #packages:

cache:
  # Maximum cache size
  #size: 1 GiB

  # The path of the cache (relative or absolute)
  #directory: cache

collector:
  # Local directory where to look for packages
  #local_directory:

  # List of repositories and their update intervals in the format [HH:MM]SS
  # E.g., http://example.com/repo/: 12:00:00
  #repositories:

auth:
  # Enable or disable authentication for requests
  #enabled: true

  # List of usernames and password hashes (SHA256)
  # E.g., tu-berlin.de: eee26bb21675236b7e98598e31d5db887cbc5d671c1d46c3e4e03e46cd3a35e0
  #users:
