####################################################
# QuestionPy Application Server Configuration File #
####################################################

# This file shows all available settings with their corresponding default values commented out.

# Every setting can be overwritten by a corresponding environment variable. The environment variable has to
# follow the pattern "QPY_<SECTION>__<SETTING>" - section and setting are uppercased and separated by two underscores.
# E.g., the setting general->log_level can be overwritten by the environment variable QPY_GENERAL__LOG_LEVEL.

general:
  # The log level [NONE, DEBUG, INFO, WARNING, ERROR, CRITICAL]
  #log_level: INFO

webservice:
  # The address the http server should bind to
  #listen_address: 127.0.0.1

  # The port the http server should bind to
  #listen_port: 9020

  # Maximum package size (at least 20 MiB)
  #max_package_size: 20 MiB

  # Allow packages from the LMS
  #allow_lms_packages: True

worker:
  # Fully qualified name of the worker class
  #type: questionpy_server.worker.impl.subprocess.SubprocessWorker

  # Maximum number of running workers
  #max_workers: 8

  # Maximum combined memory usage of all workers
  #max_memory: 500 MiB

cache:
  # Maximum cache size
  #size: 1 GiB

  # The path of the cache (relative or absolute)
  #path: cache

collector:
  # Local directory where to look for packages
  #local_directory:

  # List of repositories and their update intervals in the format [HH:MM]SS
  # E.g., http://example.com/repo/: 12:00:00
  #repositories:

auth:
  # Enable or disable authentication for requests
  #enabled: True

  # List of usernames and password hashes (SHA256)
  # E.g., tu-berlin.de: eee26bb21675236b7e98598e31d5db887cbc5d671c1d46c3e4e03e46cd3a35e0
  #users:
